# Generated by Django 4.2.13 on 2024-09-08 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("otp_totp", "0003_add_timestamps"),
        ("otp_email", "0006_add_timestamps"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDevice",
            fields=[
                (
                    "emaildevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="otp_email.emaildevice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("otp_email.emaildevice",),
        ),
        migrations.AddField(
            model_name="customuser",
            name="totp_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="otp_totp.totpdevice",
            ),
        ),
        migrations.CreateModel(
            name="SMSDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The human-readable name of this device.",
                        max_length=64,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=True, help_text="Is this device ready for use?"
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "valid_until",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The timestamp of the moment of expiry of the saved token.",
                    ),
                ),
                (
                    "throttling_failure_timestamp",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="A timestamp of the last failed verification attempt. Null if last attempt succeeded.",
                        null=True,
                    ),
                ),
                (
                    "throttling_failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successive failed attempts."
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="The mobile number to deliver tokens to (E.164).",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that this device belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Device",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.emaildevice",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sms_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.smsdevice",
            ),
        ),
    ]
