# Generated by Django 5.1.1 on 2024-09-15 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_emaildevice_customuser_totp_device_smsdevice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "This username is already taken. Please choose a different one."
                },
                max_length=30,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="username must not start with numeric values nor contains @",
                        regex="^(?!\\d)[^\\@]*$",
                    )
                ],
            ),
        ),
    ]
