# Generated by Django 5.1.1 on 2024-09-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_customuser_has_active_subscription_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="has_active_subscription",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="stripeCustomerId",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="stripeSubscriptionId",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="trial_start_date",
        ),
    ]
