# Generated by Django 4.2.13 on 2024-08-09 15:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_remove_customuser_is_phone_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "This username is already taken. Please choose a different one."
                },
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="username must not start with numeric values nor contains @",
                        regex="^(?!\\d)[^\\@]*$",
                    )
                ],
            ),
        ),
    ]
