# Generated by Django 4.2.13 on 2024-08-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_customuser_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="f_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="l_name",
            new_name="last_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
