# Generated by Django 4.2.13 on 2024-08-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="engines",
        ),
    ]
