# Generated by Django 4.2.13 on 2024-08-06 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_alter_chat_unique_together"),
        ("bookmark", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="message",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="engine.message"
            ),
        ),
    ]
