# Generated by Django 4.2.13 on 2024-08-08 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0004_alter_bookmark_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 8, 8, 12, 47, 59, 268200, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
