# Generated by Django 4.2.13 on 2024-08-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0005_bookmark_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
