# Generated by Django 4.2.13 on 2024-08-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0006_bookmark_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookmark",
            name="message",
        ),
    ]
