# Generated by Django 4.2.13 on 2024-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0007_remove_bookmark_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="id",
            field=models.CharField(
                editable=False, max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
