services:
    web:
        build: .
        restart: unless-stopped
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        depends_on:
            - redis
            - db
        env_file:
            - .env.prod

    nginx:
        build: ./nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        env_file:
            - .env.prod
        volumes:
            - /etc/letsencrypt/live/backend.rithub.org/fullchain.pem:/etc/letsencrypt/live/backend.rithub.org/fullchain.pem
            - /etc/letsencrypt/live/backend.rithub.org/privkey.pem:/etc/letsencrypt/live/backend.rithub.org/privkey.pem
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles

        depends_on:
            - web

    celery:
        build: .
        restart: unless-stopped
        command: celery -A RITengine worker -l warning --autoscale=4,2
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        depends_on:
            - redis
            - db
            - web
        env_file:
            - .env.prod

    redis:
        image: redis:latest
        restart: unless-stopped

    db:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - .env.prod

volumes:
    static_volume:
    media_volume:
    postgres_data:
