# Generated by Django 4.2.13 on 2024-07-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="legaldocument",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
