# Generated by Django 4.2.13 on 2024-08-31 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("822b7037-eb1d-4e97-ab79-fc83391feec6"),
                editable=False,
                unique=True,
            ),
        ),
    ]
