# Generated by Django 4.2.13 on 2024-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="object_id",
            field=models.CharField(max_length=6),
        ),
    ]
