# Generated by Django 4.2.13 on 2024-09-01 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0003_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("6c39f201-9f7b-4c0d-81d3-140250628a00"),
                editable=False,
                unique=True,
            ),
        ),
    ]
