# Generated by Django 4.2.13 on 2024-07-31 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0003_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("a3d6f573-f25a-4357-b2af-9ff9f104ab6f"),
                editable=False,
                unique=True,
            ),
        ),
    ]
