# Generated by Django 4.2.13 on 2024-09-02 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0004_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("3dc31eac-dec1-4b89-9968-43b5cf120063"),
                editable=False,
                unique=True,
            ),
        ),
    ]
