# Generated by Django 4.2.13 on 2024-08-01 11:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0004_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("b40470d7-c60b-4ab4-b981-eced1d5a15b6"),
                editable=False,
                unique=True,
            ),
        ),
    ]
