# Generated by Django 4.2.13 on 2024-08-05 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0006_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("fbed785f-3c61-40f7-af18-effae1b093f7"),
                editable=False,
                unique=True,
            ),
        ),
    ]
