# Generated by Django 4.2.13 on 2024-08-05 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0007_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("52123a9f-a6ce-4956-a004-88fba37fee80"),
                editable=False,
                unique=True,
            ),
        ),
    ]
