# Generated by Django 4.2.13 on 2024-08-06 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0008_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("baa20cea-aed5-43fb-a9dc-f2afd73c386d"),
                editable=False,
                unique=True,
            ),
        ),
    ]
