# Generated by Django 4.2.13 on 2024-08-07 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0009_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("f49ba1ac-9537-42cb-aeb6-2f55f5fa82bf"),
                editable=False,
                unique=True,
            ),
        ),
    ]
