# Generated by Django 4.2.13 on 2024-08-09 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0014_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("1493ba86-8f36-4678-bb39-ae9e703d844e"),
                editable=False,
                unique=True,
            ),
        ),
    ]
