# Generated by Django 4.2.13 on 2024-08-09 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0015_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("e554da94-d6f3-4367-a680-2dcd7033c906"),
                editable=False,
                unique=True,
            ),
        ),
    ]
