# Generated by Django 4.2.13 on 2024-08-11 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0016_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("7ad93794-8064-4dc7-b9c6-10e39de6a652"),
                editable=False,
                unique=True,
            ),
        ),
    ]
