# Generated by Django 4.2.13 on 2024-08-12 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0017_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("12b39183-3d43-48eb-bbf4-4ca7480373ca"),
                editable=False,
                unique=True,
            ),
        ),
    ]
