# Generated by Django 4.2.13 on 2024-08-15 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0018_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("bdcb30d5-d25c-4671-8534-93b60ffb7a61"),
                editable=False,
                unique=True,
            ),
        ),
    ]
