# Generated by Django 4.2.13 on 2024-08-18 08:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0019_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("95cb5bb2-0d41-4888-9e14-f949548b4550"),
                editable=False,
                unique=True,
            ),
        ),
    ]
