# Generated by Django 4.2.13 on 2024-08-22 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0020_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("5ea70a21-dc44-4391-a604-e181815a8040"),
                editable=False,
                unique=True,
            ),
        ),
    ]
