# Generated by Django 4.2.13 on 2024-08-22 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0021_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("7550ffd1-c6de-408a-bfb2-51888d161a85"),
                editable=False,
                unique=True,
            ),
        ),
    ]
