# Generated by Django 4.2.13 on 2024-08-22 12:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0022_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("e4acf3a8-f3a8-47f1-9810-781d2f1bb4a3"),
                editable=False,
                unique=True,
            ),
        ),
    ]
