# Generated by Django 4.2.13 on 2024-08-24 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0023_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("def9a539-a015-45b8-ad92-445882094366"),
                editable=False,
                unique=True,
            ),
        ),
    ]
