# Generated by Django 4.2.13 on 2024-08-25 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0024_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("d6227fcc-0329-4e2d-97f6-2e79a564febd"),
                editable=False,
                unique=True,
            ),
        ),
    ]
