# Generated by Django 4.2.13 on 2024-08-26 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0025_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("2fcceebb-ccb9-4c66-bcee-142126d6af97"),
                editable=False,
                unique=True,
            ),
        ),
    ]
