# Generated by Django 4.2.13 on 2024-08-26 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0026_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("89917ef9-eef9-47d7-b336-d24ae7e67321"),
                editable=False,
                unique=True,
            ),
        ),
    ]
