# Generated by Django 4.2.13 on 2024-08-26 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0027_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("10154077-e488-4a1f-9f0b-01fca2ca872b"),
                editable=False,
                unique=True,
            ),
        ),
    ]
