# Generated by Django 4.2.13 on 2024-08-27 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0029_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("5374f83f-f7b3-4afc-a855-d1453fb5b597"),
                editable=False,
                unique=True,
            ),
        ),
    ]
