# Generated by Django 4.2.13 on 2024-08-30 19:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0030_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("cd255faa-c77e-4e4a-b6f1-982ce238bdf5"),
                editable=False,
                unique=True,
            ),
        ),
    ]
