# Generated by Django 4.2.13 on 2024-08-31 20:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0031_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("c029cc71-938f-4ed9-be7f-8d0484db29de"),
                editable=False,
                unique=True,
            ),
        ),
    ]
