# Generated by Django 4.2.13 on 2024-08-31 21:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0032_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("2a1064d3-a510-4057-812c-6e3e69509f05"),
                editable=False,
                unique=True,
            ),
        ),
    ]
