# Generated by Django 4.2.13 on 2024-08-31 21:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0033_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("23a23606-9255-4644-adac-3aa283465d34"),
                editable=False,
                unique=True,
            ),
        ),
    ]
