# Generated by Django 4.2.13 on 2024-08-31 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0034_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("f43ef718-9c9c-41eb-9640-958843c57c4a"),
                editable=False,
                unique=True,
            ),
        ),
    ]
