# Generated by Django 4.2.13 on 2024-08-31 22:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0035_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("4ff63d19-ef0b-494d-bd5b-8f3634795baf"),
                editable=False,
                unique=True,
            ),
        ),
    ]
