# Generated by Django 4.2.14 on 2024-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shareable_key",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
