# Generated by Django 4.2.14 on 2024-07-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engine", "0001_initial"),
        ("bookmark", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="engine.message"
            ),
        ),
    ]
