# Generated by Django 4.2.13 on 2024-08-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=6, primary_key=True, serialize=False
                    ),
                ),
                (
                    "shareable_key",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "messages",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="engine.message"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
