# Generated by Django 4.2.13 on 2024-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_project_created_at_project_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.CharField(
                editable=False, max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
