# Generated by Django 5.1.1 on 2024-09-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="bookmarks_created",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="messages_sent_today",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="projects_created",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="plan",
            name="bookmarks_total",
            field=models.IntegerField(
                default=0, help_text="Max bookmarks allowed for the subscription period"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="messages_per_day",
            field=models.IntegerField(
                default=0, help_text="Max messages allowed per day"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="projects_total",
            field=models.IntegerField(
                default=0, help_text="Max projects allowed for the subscription period"
            ),
        ),
    ]
