# Generated by Django 5.1.1 on 2024-10-05 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_customer_bookmarks_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="stripe_price_id",
            new_name="stripe_product_id",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="bookmarks_total",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="interval_count",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="messages_per_day",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="price",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="projects_total",
        ),
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interval_count", models.IntegerField(default=1)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("week", "Week"),
                            ("month", "Month"),
                            ("year", "Year"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("usd", "USD - United States Dollar"),
                            ("eur", "EUR - Euro"),
                            ("gbp", "GBP - British Pound"),
                            ("chf", "CHF - Swiss Franc"),
                            ("aed", "AED - UAE Dirham"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="payment.plan",
                    ),
                ),
            ],
        ),
    ]
