# Generated by Django 5.1.1 on 2024-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_alter_chat_options"),
        ("payment", "0003_rename_stripe_price_id_plan_stripe_product_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="bookmarks_limit",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="engines_categories",
            field=models.ManyToManyField(to="engine.enginecategory"),
        ),
        migrations.AddField(
            model_name="plan",
            name="messages_limit",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="projects_limit",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="planprice",
            name="trial_period_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="customer",
            name="source_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("canceled", "Canceled"),
                    ("incomplete", "Incomplete"),
                    ("incomplete_expired", "Incomplete Expired"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
