# Generated by Django 5.1.1 on 2024-10-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0004_plan_bookmarks_limit_plan_engines_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planprice",
            name="trial_period_days",
        ),
    ]
