# Generated by Django 5.1.1 on 2024-10-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0005_remove_planprice_trial_period_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription",
                to="payment.customer",
            ),
        ),
    ]
