# Generated by Django 4.2.13 on 2024-09-01 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enginecategory",
            name="external_service",
        ),
        migrations.AddField(
            model_name="engine",
            name="external_service",
            field=models.CharField(
                blank=True, choices=[("darkob", "Darkob")], max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="enginecategory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 1, 9, 47, 40, 494789, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enginecategory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
