# Generated by Django 4.2.13 on 2024-09-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0003_remove_enginecategory_external_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enginecategory",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="enginecategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_engine_category",
            ),
        ),
    ]
