# Generated by Django 5.1.1 on 2024-09-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_enginecategory_is_default_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={},
        ),
    ]
