# Generated by Django 5.1.1 on 2024-10-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_alter_chat_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engine",
            name="external_service",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google_shopping_search", "Google Shopping Search"),
                    ("google_patents_search", "Google Patents Search"),
                    ("google_scholar_search", "Google Scholar Search"),
                    ("google_autocomplete_search", "Google Autocomplete Search"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
