# Generated by Django 4.2.13 on 2024-08-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0007_remove_bookmark_message"),
        ("engine", "0007_message_reply_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="reply_to",
        ),
        migrations.AddField(
            model_name="message",
            name="bookmark_collection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="bookmark.bookmark",
            ),
            preserve_default=False,
        ),
    ]
