# Generated by Django 4.2.13 on 2024-08-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0007_remove_bookmark_message"),
        ("engine", "0008_remove_message_reply_to_message_bookmark_collection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="bookmark_collection",
        ),
        migrations.AddField(
            model_name="message",
            name="bookmark",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="bookmark.bookmark",
            ),
        ),
    ]
