# Generated by Django 4.2.13 on 2024-08-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0009_remove_message_bookmark_collection_message_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="engines",
            field=models.ManyToManyField(related_name="messages", to="engine.engine"),
        ),
    ]
