# Generated by Django 4.2.13 on 2024-08-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0011_message_reply_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.CharField(
                editable=False, max_length=6, primary_key=True, serialize=False
            ),
        ),
    ]
