# Generated by Django 4.2.13 on 2024-08-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0012_alter_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="enginecategory",
            name="base_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enginecategory",
            name="external_service",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
