# Generated by Django 4.2.13 on 2024-08-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0013_enginecategory_base_prompt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enginecategory",
            name="external_service",
            field=models.CharField(
                blank=True, choices=[("darkob", "Darkob")], max_length=255, null=True
            ),
        ),
    ]
