# Generated by Django 4.2.13 on 2024-08-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0014_alter_enginecategory_external_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engine",
            name="prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
