# Generated by Django 4.2.13 on 2024-08-31 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0015_alter_engine_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="engine",
            name="category",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="engines",
                to="engine.enginecategory",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="enginecategory",
            name="base_prompt",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
