# Generated by Django 4.2.13 on 2024-08-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0016_alter_engine_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enginecategory",
            name="base_prompt",
        ),
    ]
