# Generated by Django 4.2.13 on 2024-08-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legaldocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("privacy_policy", "Privacy Policy"),
                    ("user_guide", "User Guide"),
                    ("terms_of_use", "Terms of Use"),
                    ("faq", "Ferequently Asked Questions"),
                    ("license", "License"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
