# Generated by Django 4.2.13 on 2024-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0003_alter_legaldocument_doc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=150)),
                ("answer", models.TextField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="legaldocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("privacy_policy", "Privacy Policy"),
                    ("user_guide", "User Guide"),
                    ("terms_of_use", "Terms of Use"),
                    ("license", "License"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
