# Generated by Django 4.2.14 on 2024-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shareable_key",
                    models.UUIDField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="assets/projects/"
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="projects",
                        to="engine.message",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
