# Generated by Django 4.2.13 on 2024-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_bookmark"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="assets/projects/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="messages",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="projects", to="engine.message"
            ),
        ),
    ]
