# Generated by Django 4.2.13 on 2024-07-25 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0002_alter_project_description_alter_project_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="shareable_key",
            field=models.CharField(
                blank=True, editable=False, max_length=8, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="viewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)s_viewers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_%(class)ss",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
