# Generated by Django 4.2.13 on 2024-07-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_initial"),
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="messages",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="engine.message"
            ),
        ),
    ]
