# Generated by Django 4.2.13 on 2024-07-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_project_shareable_key_project_viewers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="shareable_key",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
