# Generated by Django 4.2.13 on 2024-08-05 20:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0003_alter_project_messages"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("user", "id")},
        ),
    ]
