# Generated by Django 4.2.13 on 2024-08-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_alter_project_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together=set(),
        ),
    ]
