# Generated by Django 5.1.1 on 2024-11-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventions",
            "0004_alter_form_office_alter_form_slug_alter_office_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
