# Generated by Django 4.2.14 on 2024-07-31 12:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("otp_email", "0001_initial"),
        ("otp_totp", "0001_initial"),
        ("otp_twilio", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_twilio.twiliosmsdevice",),
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "username",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="username must not start with numeric values nor contains @",
                                regex="^(?!\\d)[^\\@]*$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("f_name", models.CharField(blank=True, max_length=50, null=True)),
                ("l_name", models.CharField(blank=True, max_length=50, null=True)),
                ("inv_code", models.CharField(blank=True, max_length=17, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("role", models.CharField(blank=True, max_length=50, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_oauth_based", models.BooleanField(default=False)),
                ("otp_secret", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "preferred_2fa",
                    models.CharField(
                        blank=True,
                        choices=[("email", "Email"), ("sms", "SMS"), ("totp", "TOTP")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "email_device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="otp_email.emaildevice",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "sms_device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.smsdevice",
                    ),
                ),
                (
                    "totp_device",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="otp_totp.totpdevice",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
