# Generated by Django 4.2.13 on 2024-07-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("otp_twilio", "0004_sidechanneldevice"),
        ("otp_totp", "0003_add_timestamps"),
        ("otp_email", "0006_add_timestamps"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_twilio.twiliosmsdevice",),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="otp_email.emaildevice",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="totp_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="otp_totp.totpdevice",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sms_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.smsdevice",
            ),
        ),
    ]
