# Generated by Django 4.2.13 on 2024-07-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="otp_expiry_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
