# Generated by Django 4.2.13 on 2024-07-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("otp_totp", "0003_add_timestamps"),
        ("otp_email", "0006_add_timestamps"),
        ("user", "0002_customuser_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="otp_email.emaildevice",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="preferred_2fa",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("sms", "SMS"), ("totp", "TOTP")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="totp_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="otp_totp.totpdevice",
            ),
        ),
    ]
