# Generated by Django 4.2.13 on 2024-07-07 19:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_image_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_two_fa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="two_fa_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email_otp", "Email OTP"),
                    ("sms_otp", "SMS OTP"),
                    ("google_auth", "Google Authenticator"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="username must not start with numeric values nor contains @",
                        regex="^(?!\\d)[^\\@]*$",
                    )
                ],
            ),
        ),
    ]
