# Generated by Django 4.2.13 on 2024-07-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_otp_customuser_otp_expiry_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_otp_verified",
            field=models.BooleanField(default=False),
        ),
    ]
