# Generated by Django 4.2.13 on 2024-07-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_is_two_fa_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="totp_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
