# Generated by Django 4.2.13 on 2024-07-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_customuser_email_device_customuser_preferred_2fa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_2fa_enabled",
        ),
    ]
