# Generated by Django 4.2.13 on 2024-07-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_customuser_is_2fa_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_oauth_based",
            field=models.BooleanField(default=False),
        ),
    ]
