# Generated by Django 4.2.13 on 2024-08-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_customuser_is_phone_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_phone_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="otp_secret",
        ),
    ]
