# Generated by Django 4.2.13 on 2024-07-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_customuser_is_oauth_based"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
