# Generated by Django 4.2.13 on 2024-07-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("otp_twilio", "0004_sidechanneldevice"),
        ("user", "0006_customuser_is_staff_alter_customuser_is_superuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSDevice",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_twilio.twiliosmsdevice",),
        ),
        migrations.AddField(
            model_name="customuser",
            name="sms_device",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.smsdevice",
            ),
        ),
    ]
