# Generated by Django 4.2.13 on 2024-07-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="message",
            name="updated_at",
        ),
    ]
