# Generated by Django 4.2.13 on 2024-07-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0002_alter_message_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
    ]
