# Generated by Django 4.2.13 on 2024-08-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_alter_chat_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together=set(),
        ),
    ]
