# Generated by Django 4.2.13 on 2024-07-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0004_bookmark"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bookmark",
        ),
    ]
