# Generated by Django 4.2.13 on 2024-07-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_chat_shareable_key_chat_viewers_alter_chat_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="shareable_key",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
