# Generated by Django 4.2.13 on 2024-07-26 09:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessrequest",
            old_name="approved",
            new_name="is_approved",
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("b6670de2-5ae0-433d-aaba-fbcd9eb458fa"),
                editable=False,
                unique=True,
            ),
        ),
    ]
