# Generated by Django 4.2.13 on 2024-07-26 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0002_rename_approved_accessrequest_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("4dc53272-e982-424c-bb36-7243a50ffd75"),
                editable=False,
                unique=True,
            ),
        ),
    ]
