# Generated by Django 4.2.13 on 2024-07-27 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0003_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("d75e890f-5396-4b93-9c38-88eea143a008"),
                editable=False,
                unique=True,
            ),
        ),
    ]
