# Generated by Django 4.2.13 on 2024-08-04 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0005_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("9a82aadd-b2f6-48d9-86ba-8895a56a7c0e"),
                editable=False,
                unique=True,
            ),
        ),
    ]
