# Generated by Django 4.2.13 on 2024-08-08 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0010_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("ea2996b7-5970-4a5b-89ed-434466f27c8a"),
                editable=False,
                unique=True,
            ),
        ),
    ]
