# Generated by Django 4.2.13 on 2024-08-08 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0011_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("cf80abf1-765a-44b0-af8b-435cb8ae4dda"),
                editable=False,
                unique=True,
            ),
        ),
    ]
