# Generated by Django 4.2.13 on 2024-08-08 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("share", "0012_alter_accessrequest_approval_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="approval_uuid",
            field=models.UUIDField(
                default=uuid.UUID("dd1f97f0-43ca-42e9-998e-aa581fdc4ff1"),
                editable=False,
                unique=True,
            ),
        ),
    ]
